Repository graasp/graasp-auth, pull requests merged in 2023-07, with the labels that each got.

#107 feat(style): revamp of the login page
  cypress/support/commands.ts
  src/components/FullscreenContainer.tsx
  src/components/SignIn.tsx
  src/components/SignUp.tsx
  src/components/StyledTextField.tsx
  src/components/SuccessContent.tsx
Labels: improvement

#113 fix(deps): update graasp deps
  package.json
  yarn.lock
Labels: chore, dependencies

#102 feat: add mobile auth through 'm' query parameter
  cypress.config.ts
  package.json
  src/components/SignIn.tsx
  src/components/UserSwitch.tsx
  src/hooks/mobile.tsx
  yarn.lock
Labels: feature
