Repository graasp/graasp-auth, pull requests merged in 2024-04, with the labels that each got.

#356 fix: allow no recaptcha key in dev
  .eslintrc
  src/context/RecaptchaContext.tsx
Labels: bug

#363 fix: update loading buttons, add error messages
  README.md
  cypress.config.ts
  cypress/e2e/SignIn.cy.ts
  cypress/e2e/SignUp.cy.ts
  cypress/fixtures/members.ts
  cypress/support/server.ts
  index.html
  package.json
  src/App.tsx
  src/Root.tsx
  src/components/EmailInput.tsx
  src/components/SignIn.tsx
  src/components/SignUp.tsx
  src/components/StyledTextField.tsx
  src/components/common/ErrorDisplay.tsx
  src/config/constants.ts
  src/config/messages.ts
  src/config/notifier.ts
  src/env.d.ts
  src/langs/constants.ts
  src/langs/en.json
  src/utils/validation.ts
  yarn.lock
Labels: improvement

#373 feat: regroup the API Alert with the Form container
  src/components/FullscreenContainer.tsx
Labels: improvement

#378 fix: vite config
  package.json
  vite.config.ts
  yarn.lock
Labels: chore
