Repository graasp/graasp-auth, pull requests merged in 2024-09, with the labels that each got.

#442 fix: update ui to use ts build
  .husky/commit-msg
  .husky/post-commit
  .husky/pre-commit
  .husky/pre-push
  cypress/support/server.ts
  package.json
  yarn.lock
Labels: dependencies

#413 feat: show different success message for password on success, refactor
  cypress/e2e/SignIn.cy.ts
  cypress/e2e/SignInPassword.cy.ts
  cypress/e2e/SuccessContent.cy.ts
  cypress/e2e/util.ts
  cypress/support/commands.ts
  src/App.tsx
  src/components/APIChecker.tsx
  src/components/AgreementForm.tsx
  src/components/EmailInput.tsx
  src/components/EnableAnalyticsForm.tsx
  src/components/FullscreenContainer.tsx
  src/components/LeftContentContainer.tsx
  src/components/MagicLinkForm.tsx
  src/components/MagicLinkSuccessContent.tsx
  src/components/MobileAuth.tsx
  src/components/SignIn.tsx
  src/components/SignInPasswordForm.tsx
  src/components/SignUp.tsx
  src/components/SuccessContent.tsx
  src/components/common/PasswordInput.tsx
  src/components/leftContent/AnalyticsContent.tsx
  src/components/leftContent/BuilderContent.tsx
  src/components/leftContent/LibraryContent.tsx
  src/components/leftContent/PlayerContent.tsx
  src/config/paths.ts
  src/config/selectors.ts
  src/langs/constants.ts
  src/langs/en.json
  src/langs/fr.json
Labels: un-released

#446 chore(main): release 2.6.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#452 fix: update dependencies and yarn version
  .yarn/releases/yarn-4.3.1.cjs
  .yarn/releases/yarn-4.5.0.cjs
  .yarnrc.yml
  cypress/fixtures/members.ts
  package.json
  tsconfig.json
  yarn.lock
Labels: chore, dependencies
