Repository graasp/graasp-auth, pull requests merged in 2024-10, with the labels that each got.

#462 fix: enable TS strict mode
  cypress/e2e/util.ts
  cypress/support/commands.ts
  cypress/support/server.ts
  cypress/tsconfig.json
  package.json
  src/Root.tsx
  src/components/EmailInput.tsx
  src/components/MagicLinkSuccessContent.tsx
  src/components/SignUp.tsx
  src/components/common/ErrorDisplay.tsx
  src/components/common/PasswordInput.tsx
  src/config/notifier.ts
  src/context/RecaptchaContext.tsx
  src/hooks/mobile.tsx
  tsconfig.json
  yarn.lock
Labels: build

#414 feat: add reset password forms
  .github/workflows/cypress.yml
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-stage.yml
  README.md
  cypress/e2e/SignInPassword.cy.ts
  cypress/e2e/requestPasswordReset.cy.ts
  cypress/e2e/resetPassword.cy.ts
  cypress/e2e/util.ts
  cypress/fixtures/members.ts
  cypress/support/commands.ts
  cypress/support/server.ts
  package.json
  src/App.tsx
  src/components/APIChecker.tsx
  src/components/EmailInput.tsx
  src/components/LeftContentContainer.tsx
  src/components/Redirection.tsx
  src/components/SignIn.tsx
  src/components/SignUp.tsx
  src/components/StyledDivider.tsx
  src/components/common/EmailAdornment.tsx
  src/components/common/ErrorDisplay.tsx
  src/components/common/PasswordInput.tsx
  src/components/common/StyledTextField.tsx
  src/components/layout/CenteredContent.tsx
  src/components/layout/DialogHeader.tsx
  src/components/register/AgreementForm.tsx
  src/components/register/EnableAnalyticsForm.tsx
  src/components/requestPasswordReset/InvalidTokenScreen.tsx
  src/components/requestPasswordReset/RequestPasswordReset.tsx
  src/components/requestPasswordReset/ResetPassword.tsx
  src/components/signIn/MagicLinkForm.tsx
  src/components/signIn/PasswordForm.tsx
  src/components/styles.ts
  src/config/constants.ts
  src/config/env.ts
  src/config/messages.ts
  src/config/paths.ts
  src/config/selectors.ts
  src/env.d.ts
  src/hooks/mobile.tsx
  src/hooks/searchParams.tsx
  src/hooks/useValidateJWTToken.ts
  src/langs/constants.ts
  src/langs/en.json
  src/utils/validation.ts
  vite.config.ts
  yarn.lock
Labels: feature

#463 fix: update dependencies
  package.json
  src/components/SignUp.tsx
  src/components/requestPasswordReset/RequestPasswordReset.tsx
  src/components/requestPasswordReset/ResetPassword.tsx
  src/components/signIn/MagicLinkForm.tsx
  src/components/signIn/PasswordForm.tsx
  yarn.lock
Labels: dependencies

#453 chore(main): release 2.7.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#470 chore(main): release 2.7.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#480 fix: update message show on password reset error
  src/langs/en.json
Labels: chore

#482 chore(main): release 2.7.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#485 fix: make redirection screen more user friendly
  .github/workflows/cypress.yml
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-stage.yml
  README.md
  cypress.config.ts
  cypress/e2e/SignIn.cy.ts
  cypress/support/commands.ts
  cypress/support/server.ts
  src/components/Redirection.tsx
  src/config/env.ts
  src/config/selectors.ts
  src/langs/constants.ts
  src/langs/en.json
Labels: bug

#486 chore(main): release 2.7.3
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#489 fix: message shown on the button when reset is success
  cypress/e2e/resetPassword.cy.ts
  src/components/SignUp.tsx
  src/components/requestPasswordReset/ResetPassword.tsx
  src/config/selectors.ts
  src/langs/constants.ts
  src/langs/en.json
Labels: bug

#483 fix: validate email with enter
  .eslintrc
  cypress/e2e/SignIn.cy.ts
  cypress/e2e/SignInWithStoredSession.cy.ts
  cypress/e2e/register.cy.ts
  cypress/e2e/signinWithPassword.cy.ts
  cypress/e2e/util.ts
  cypress/support/commands.ts
  cypress/support/server.ts
  src/App.tsx
  src/Root.tsx
  src/components/APIChecker.tsx
  src/components/BrandingLogo.tsx
  src/components/ErrorFallback.tsx
  src/components/Footer.tsx
  src/components/LeftContentContainer.tsx
  src/components/MagicLinkSuccessContent.tsx
  src/components/MobileAuth.tsx
  src/components/Redirection.tsx
  src/components/common/Adornments.tsx
  src/components/common/EmailAdornment.tsx
  src/components/common/ErrorDisplay.tsx
  src/components/common/PasswordInput.tsx
  src/components/common/StyledTextField.tsx
  src/components/layout/CenteredContent.tsx
  src/components/layout/DialogHeader.tsx
  src/components/leftContent/PlatformContent.tsx
  src/components/register/AgreementForm.tsx
  src/components/register/EmailInput.tsx
  src/components/register/EnableAnalyticsForm.tsx
  src/components/register/Register.tsx
  src/components/requestPasswordReset/InvalidTokenScreen.tsx
  src/components/requestPasswordReset/RequestPasswordReset.tsx
  src/components/requestPasswordReset/ResetPassword.tsx
  src/components/signIn/EmailInput.tsx
  src/components/signIn/MagicLinkForm.tsx
  src/components/signIn/PasswordForm.tsx
  src/components/signIn/SignIn.tsx
  src/config/selectors.ts
  src/context/RecaptchaContext.tsx
  src/main.tsx
Labels: bug

#495 fix: upgrade to mui v6
  package.json
  yarn.lock
Labels: chore, dependencies

#492 chore(main): release 2.7.4
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#500 chore(main): release 2.7.5
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#503 fix: password icon use lock icon
  src/components/common/Adornments.tsx
  src/components/common/PasswordInput.tsx
  src/components/requestPasswordReset/ResetPassword.tsx
Labels: chore
